# Site settings
title: Kevin Zita
email: kevin@kzisme.com
description: > # this means to ignore newlines until "baseurl:"
    #Empty until I figure out if I want something here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kzisme
github_username:  kzisme

# Build settings
markdown: kramdown
